🔧  Further Configuration
ministryofjustice/analytical-platform-ollamate pull request #5
Opened 2024-07-02 14:54 UTC by Gary-H9

This PR relates to this PR

2024-07-11 16:11 UTC, jacobwoffenden requested changes, later dismissed

2024-07-11 16:11 UTC, jacobwoffenden commented on .devcontainer/devcontainer.json
> +      "version": "20.11.1"
```suggestion
      "version": "20.15.1"
```

2024-07-11 16:11 UTC, jacobwoffenden commented on .github/CODEOWNERS
> +@ministryofjustice/analytical-platforms
```suggestion
@ministryofjustice/analytical-platform
```

2024-07-11 16:11 UTC, jacobwoffenden commented on .github/workflows/build-test.yml
> +          tags: dashboard
```suggestion
          tags: ollamate
```

2024-07-11 16:11 UTC, jacobwoffenden commented on .github/workflows/dependency-review.yml
this is rolling back versions

2024-07-11 16:11 UTC, jacobwoffenden commented on .github/workflows/release.yml
Indentation is wrong

2024-07-11 16:11 UTC, jacobwoffenden commented on .github/workflows/scan-image.yml
Indentation is wrong

2024-07-11 16:11 UTC, jacobwoffenden commented on README.md
`template-repository` needs replacing in standards URL

2024-07-15 11:06 UTC, Gary-H9 commented on .github/workflows/scan-image.yml
Resolved

2024-07-15 11:06 UTC, Gary-H9 commented on .github/workflows/release.yml
Resolved

2024-07-15 11:06 UTC, Gary-H9 commented on .github/workflows/dependency-review.yml
Resolved

2024-07-15 11:14 UTC, jacobwoffenden approved these changes

2024-07-15 11:19 UTC, jacobwoffenden requested changes

2024-07-15 11:19 UTC, jacobwoffenden commented on .github/workflows/codeql-analysis.yml
> +        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
4.1.7 is available now

2024-07-15 11:19 UTC, jacobwoffenden commented on README.md
> +[![repo standards badge](https://img.shields.io/endpoint?labelColor=231f20&color=005ea5&style=for-the-badge&label=MoJ%20Compliant&url=https%3A%2F%2Foperations-engineering-reports.cloud-platform.servi
```suggestion
[![repo standards badge](https://img.shields.io/endpoint?labelColor=231f20&color=005ea5&style=for-the-badge&label=MoJ%20Compliant&url=https%3A%2F%2Foperations-engineering-reports.cloud-platform.service.justice.gov.uk%2Fapi%2Fv1%2Fcompliant_public_repositories%2Fendpoint%2Fanalytical-platform-ollamate&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAHJElEQVRYhe2YeYyW1RWHnzuMCzCIglBQlhSV2gICKlHiUhVBEAsxGqmVxCUUIV1i61YxadEoal1SWttUaKJNWrQUsRRc6tLGNlCXWGyoUkCJ4uCCSCOiwlTm6R/nfPjyMeDY8lfjSSZz3/fee87vnnPu75z3g8/kM2mfqMPVH6mf35t6G/ZgcJ/836Gdug4FjgO67UFn70+FDmjcw9xZaiegWX29lLLmE3QV4Glg8x7WbFfHlFIebS/ANj2oDgX+CXwA9AMubmPNvuqX1SnqKGAT0BFoVE9UL1RH7nSCUjYAL6rntBdg2Q3AgcAo4HDgXeBAoC+wrZQyWS3AWcDSUsomtSswEtgXaAGWlVI2q32BI0spj9XpPww4EVic88vaC7iq5Hz1BvVf6v3qe+rb6ji1p3pWrmtQG9VD1Jn5br+Knmm70T9MfUh9JaPQZu7uLsR9gEsJb3QF9gOagO7AuUTom1LpCcAkoCcwQj0VmJregzaipA4GphNe7w/MBearB7QLYCmlGdiWSm4CfplTHwBDgPHAFmB+Ah8N9AE6EGkxHLhaHU2kRhXc+cByYCqROs05NQq4oR7Lnm5xE9AL+GYC2gZ0Jmjk8VLKO+pE4HvAyYRnOwOH5N7NhMd/WKf3beApYBWwAdgHuCLn+tatbRtgJv1awhtd838LEeq30/A7wN+AwcBt+bwpD9AdOAkYVkpZXtVdSnlc7QI8BlwOXFmZ3oXkdxfidwmPrQXeA+4GuuT08QSdALxC3OYNhBe/TtzON4EziZBXD36o+q082BxgQuqvyYL6wtBY2TyEyJ2DgAXAzcC1+Xxw3RlGqiuJ6vE6QS9VGZ/7H02DDwAvELTyMDAxbfQBvggMAAYR9LR9J2cluH7AmnzuBowFFhLJ/wi7yiJgGXBLPq8A7idy9kPgvAQPcC9wERHSVcDtCfYj4E7gr8BRqWMjcXmeB+4tpbyG2kG9Sl2tPqF2Uick8B+7szyfvDhR3Z7vvq/2yqpynnqNeoY6v7LvevUU9QN1fZ3OTeppWZmeyzRoVu+rhbaHOledmoQ7LRd3SzBVeUo9Wf1DPs9X90/jX8m/e9Rn1Mnqi7nuXXW5+rK6oU7n64mjszovxyvVh9WeDcTVnl5KmQNcCMwvpbQA1xE8VZXhwDXAz4FWIkfnAlcBAwl6+SjD2wTcmPtagZnAEuA3dTp7qyNKKe8DW9UeBCeuBsbsWKVOUPvn+MRKCLeq16lXqLPVFvXb6r25dlaGdUx6cITaJ8fnpo5WI4Wuzcjcqn5Y8eI/1F+n3XvUA1N3v4ZamIEtpZRX1Y6Z/DUK2g84GrgHuDqTehpBCYend94jbnJ34DDgNGArQT9bict3Y3p1ZCnlSoLQb0sbgwjCXpY2blc7llLW1UAMI3o5CD4bmuOlwHaC6xakgZ4Z+ibgSxnOgcAI4uavI27jEII7909dL5VSrimlPKgeQ6TJCZVQjwaOLaW8BfyWbPEa1SaiTH1VfSENd85NDxHt1plA71LKRvX4BDaAKFlTgLeALtliDUqPrSV6SQCBlypgFlbmIIrCDcAl6nPAawmYhlLKFuB6IrkXAadUNj6TXlhDcCNEB/Jn4FcE0f4UWEl0NyWNvZxGTs89z6ZnatIIrCdqcCtRJmcCPwCeSN3N1Iu6T4VaFhm9n+riypouBnepLsk9p6p35fzwvDSX5eVQvaDOzjnqzTl+1KC53+XzLINHd65O6lD1DnWbepPBhQ3q2jQyW+2oDkkAtdt5udpb7W+Q/OFGA7ol1zxu1tc8zNHqXercfDfQIOZm9fR815Cpt5PnVqsr1F51wI9QnzU63xZ1o/rdPPmt6enV6sXqHPVqdXOCe1rtrg5W7zNI+m712Ir+cer4POiqfHeJSVe1Raemwnm7xD3mD1E/Z3wIjcsTdlZnqO8bFeNB9c30zgVG2euYa69QJ+9G90lG+99bfdIoo5PU4w362xHePxl1slMab6tV72KUxDvzlAMT8G0ZohXq39VX1bNzzxij9K1Qb9lhdGe931B/kR6/zCwY9YvuytCsMlj+gbr5SemhqkyuzE8xau4MP865JvWNuj0b1YuqDkgvH2GkURfakly01Cg7Cw0+qyXxkjojq9Lw+vT2AUY+DlF/otYq1Ixc35re2V7R8aTRg2KUv7+ou3x/14PsUBn3NG51S0XpG0Z9PcOPKWSS0SKNUo9Rv2Mmt/G5WpPF6pHGra7Jv410OVsdaz217AbkAPX3ubkm240belCuudT4Rp5p/DyC2lf9mfq1iq5eFe8/lu+K0YrVp0uret4nAkwlB6vzjI/1PxrlrTp/oNHbzTJI92T1qAT+BfW49MhMg6JUp7ehY5a6Tl2jjmVvitF9fxo5Yq8CaAfAkzLMnySt6uz/1k6bPx59CpCNxGfoSKA30IPoH7cQXdArwCOllFX/i53P5P9a/gNkKpsCMFRuFAAAAABJRU5ErkJggg==)](https://operations-engineering-reports.cloud-platform.service.justice.gov.uk/public-report/analytical-platform-ollamate)
```

2024-07-15 11:19 UTC, jacobwoffenden commented on chart/templates/.helpers.tpl
Replace references to `actions-runner` in the chart

2024-07-15 11:19 UTC, jacobwoffenden commented on chart/values.yaml
> +  tag: 0.0.1
```suggestion
  tag: ""
```
Set to blank to use `appVersion`

2024-07-15 11:19 UTC, jacobwoffenden commented on chart/values.yaml
> +    memory: "7Gi"
```suggestion
resources:
  requests:
    cpu: 1
    memory: "5Gi"
  limits:
    cpu: 2
    memory: "7Gi"
```
These probably want tuning

2024-07-15 11:19 UTC, jacobwoffenden commented on chart/values.yaml
> +    labels:
This can go

2024-07-15 11:19 UTC, jacobwoffenden commented on chart/values.yaml
> +    pollingInterval: 30
This can go as well

2024-07-15 11:23 UTC, Gary-H9 commented on chart/values.yaml
> +    labels:
✅

2024-07-15 11:23 UTC, Gary-H9 commented on chart/values.yaml
> +    pollingInterval: 30
✅

2024-07-15 11:24 UTC, Gary-H9 commented on chart/values.yaml
> +  tag: 0.0.1
✅

2024-07-15 11:32 UTC, Gary-H9 commented on .github/workflows/codeql-analysis.yml
> +        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
Updated across all workflows.

2024-07-15 11:35 UTC, Gary-H9 commented on chart/values.yaml
> +    memory: "7Gi"
Tuned down, can be altered when built

2024-07-15 11:46 UTC, jacobwoffenden approved these changes

2024-07-15 11:56 UTC, merged